global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['movie-evaluator-app:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']